sonar.projectKey=na1rob1_uptime-monitor
sonar.organization=na1rob1-1

sonar.sources=cmd,handlers,checker,repository,models,frontend/src
sonar.tests=handlers,repository,checker,frontend/src
sonar.test.inclusions=**/*_test.go,**/*.test.js,**/*.test.jsx

sonar.exclusions=**/node_modules/**,**/*_test.go,**/*.test.js,**/*.test.jsx,frontend/build/**

sonar.coverage.exclusions=cmd/server/main.go,models/**,**/*.test.js,**/*.test.jsx,**/*_test.go,frontend/src/index.js,frontend/src/reportWebVitals.js,frontend/src/setupTests.js

sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info