apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: app
data:
  001_create_sites.sql: |
    CREATE TABLE Sites (
        id SERIAL PRIMARY KEY,
        url varchar(255),
        name varchar(255),
        status BOOL DEFAULT false,
        uptime REAL,
        checked_at timestamptz,
        created_at timestamptz DEFAULT NOW(),
        total_checks INT DEFAULT 0,
        up_checks INT DEFAULT 0
    );
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: app
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: mirror.gcr.io/library/postgres:16-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "uptime"
            - name: POSTGRES_PASSWORD
              value: "uptime_pass"
            - name: POSTGRES_DB
              value: "uptime"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          resources:/
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "uptime"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nvme.network-drives.csi.timeweb.cloud
        resources:
          requests:
            storage: 1Gi