apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-monitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/na1rob1/uptime-monitor.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true